// Code generated by MockGen. DO NOT EDIT.
// Source: kubernetes_fake_test.go

package mock_kubernetes

import (
	gomock "github.com/golang/mock/gomock"
	api "github.com/hashicorp/vault/api"
)

// MockFakeClient is a mock of FakeClient interface
type MockFakeClient struct {
	ctrl     *gomock.Controller
	recorder *MockFakeClientMockRecorder
}

// MockFakeClientMockRecorder is the mock recorder for MockFakeClient
type MockFakeClientMockRecorder struct {
	mock *MockFakeClient
}

// NewMockFakeClient creates a new mock instance
func NewMockFakeClient(ctrl *gomock.Controller) *MockFakeClient {
	mock := &MockFakeClient{ctrl: ctrl}
	mock.recorder = &MockFakeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockFakeClient) EXPECT() *MockFakeClientMockRecorder {
	return _m.recorder
}

// Logical mocks base method
func (_m *MockFakeClient) Logical() *api.Logical {
	ret := _m.ctrl.Call(_m, "Logical")
	ret0, _ := ret[0].(*api.Logical)
	return ret0
}

// Logical indicates an expected call of Logical
func (_mr *MockFakeClientMockRecorder) Logical() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Logical")
}
